// Code generated by MockGen. DO NOT EDIT.
// Source: ../../../../nfl/data-access/http/scraper/scraper.go

// Package mocks is a generated GoMock package.
package mocks

import (
	"github.com/rmarken5/mini-score/service/internal/nfl/logic/internal/data-access/http/scraper"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockScheduleScraper is a mock of ScheduleScraper interface.
type MockScheduleScraper struct {
	ctrl     *gomock.Controller
	recorder *MockScheduleScraperMockRecorder
}

// MockScheduleScraperMockRecorder is the mock recorder for MockScheduleScraper.
type MockScheduleScraperMockRecorder struct {
	mock *MockScheduleScraper
}

// NewMockScheduleScraper creates a new mock instance.
func NewMockScheduleScraper(ctrl *gomock.Controller) *MockScheduleScraper {
	mock := &MockScheduleScraper{ctrl: ctrl}
	mock.recorder = &MockScheduleScraperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScheduleScraper) EXPECT() *MockScheduleScraperMockRecorder {
	return m.recorder
}

// FetchGameInfo mocks base method.
func (m *MockScheduleScraper) FetchGameInfo(gameID string) (scraper.GameInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchGameInfo", gameID)
	ret0, _ := ret[0].(scraper.GameInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchGameInfo indicates an expected call of FetchGameInfo.
func (mr *MockScheduleScraperMockRecorder) FetchGameInfo(gameID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchGameInfo", reflect.TypeOf((*MockScheduleScraper)(nil).FetchGameInfo), gameID)
}

// FetchGamesForWeek mocks base method.
func (m *MockScheduleScraper) FetchGamesForWeek(week scraper.Week) (scraper.Games, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchGamesForWeek", week)
	ret0, _ := ret[0].(scraper.Games)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchGamesForWeek indicates an expected call of FetchGamesForWeek.
func (mr *MockScheduleScraperMockRecorder) FetchGamesForWeek(week interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchGamesForWeek", reflect.TypeOf((*MockScheduleScraper)(nil).FetchGamesForWeek), week)
}

// FetchGamesForWeeks mocks base method.
func (m *MockScheduleScraper) FetchGamesForWeeks(weeks []scraper.Week) (scraper.Games, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchGamesForWeeks", weeks)
	ret0, _ := ret[0].(scraper.Games)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchGamesForWeeks indicates an expected call of FetchGamesForWeeks.
func (mr *MockScheduleScraperMockRecorder) FetchGamesForWeeks(weeks interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchGamesForWeeks", reflect.TypeOf((*MockScheduleScraper)(nil).FetchGamesForWeeks), weeks)
}

// FetchSchedule mocks base method.
func (m *MockScheduleScraper) FetchSchedule() (scraper.BySeasonType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchSchedule")
	ret0, _ := ret[0].(scraper.BySeasonType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchSchedule indicates an expected call of FetchSchedule.
func (mr *MockScheduleScraperMockRecorder) FetchSchedule() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchSchedule", reflect.TypeOf((*MockScheduleScraper)(nil).FetchSchedule))
}
