insert into TEAM (name, abbreviation) values ('New York Jets', 'NYJ');
insert into TEAM (name, abbreviation) values ('Buffalo Bills', 'BUF');
insert into TEAM (name, abbreviation) values ('Kansas City Chiefs', 'KC');
insert into TEAM (name, abbreviation) values ('Detroit Lions', 'DET');
insert into TEAM (name, abbreviation) values ('Atlanta Falcons', 'ATL');
insert into TEAM (name, abbreviation) values ('Carolina Panthers', 'CAR');
insert into TEAM (name, abbreviation) values ('Cleveland Browns', 'CLE');
insert into TEAM (name, abbreviation) values ('Cincinnati Bengals', 'CIN');
insert into TEAM (name, abbreviation) values ('Indianapolis Colts', 'IND');
insert into TEAM (name, abbreviation) values ('Jacksonville Jaguars', 'JAX');
insert into TEAM (name, abbreviation) values ('Minnesota Vikings', 'MIN');
insert into TEAM (name, abbreviation) values ('Tampa Bay Buccaneers', 'TB');
insert into TEAM (name, abbreviation) values ('New Orleans Saints', 'NO');
insert into TEAM (name, abbreviation) values ('Tennessee Titans', 'TEN');
insert into TEAM (name, abbreviation) values ('Pittsburgh Steelers', 'PIT');
insert into TEAM (name, abbreviation) values ('San Francisco 49ers', 'SF');
insert into TEAM (name, abbreviation) values ('Washington Commanders', 'WSH');
insert into TEAM (name, abbreviation) values ('Arizona Cardinals', 'ARI');
insert into TEAM (name, abbreviation) values ('Baltimore Ravens', 'BAL');
insert into TEAM (name, abbreviation) values ('Houston Texans', 'HOU');
insert into TEAM (name, abbreviation) values ('Chicago Bears', 'CHI');
insert into TEAM (name, abbreviation) values ('Green Bay Packers', 'GB');
insert into TEAM (name, abbreviation) values ('Denver Broncos', 'DEN');
insert into TEAM (name, abbreviation) values ('Las Vegas Raiders', 'LV');
insert into TEAM (name, abbreviation) values ('New England Patriots', 'NE');
insert into TEAM (name, abbreviation) values ('Philadelphia Eagles', 'PHI');
insert into TEAM (name, abbreviation) values ('Los Angeles Chargers', 'LAC');
insert into TEAM (name, abbreviation) values ('Miami Dolphins', 'MIA');
insert into TEAM (name, abbreviation) values ('Seattle Seahawks', 'SEA');
insert into TEAM (name, abbreviation) values ('Los Angeles Rams', 'LAR');
insert into TEAM (name, abbreviation) values ('New York Giants', 'NYG');
insert into TEAM (name, abbreviation) values ('Dallas Cowboys', 'DAL');
